### ISSUE TITLE
HLQ005: Single is not about performance

### ISSUE THREAD

**Issue by paulomorgado** [NetFabric/NetFabric.Hyperlinq.Analyzer#32]
The documentation for [`Enumerable.Single`](https://docs.microsoft.com/dotnet/api/system.linq.enumerable.single) states:

> Returns the only element of a sequence, and throws an exception if there is not exactly one element in the sequence.

If any of the `Single` operators is being used to get the first item, then it's being as wrongly used as using the `First` operators to the the single item.

If query a service for a customer ID and the service returns 2 different customers with the same ID, than something went wrong and you must stop what you're doing. `Single` assures you that, `First` allows your to add to the problem.

When you go to a parking lot, you park **your car** on the **first** available spot. When you leave, you get the **single** car - **your car** - not the first one you find. At least, most of society hopes you do. 😄

**Comment by aalmada** [comment]
@paulomorgado May be controversial but here's my reasoning.

Imagine that you have a large set of customers in memory. The customer with id 0 is the first one and there's only one.

You then use `.Single(customer => customer.Id == 0)` to get a customer. LINQ operators can only do a sequential search. This means it starts from the beginning of the collection and finds there the customer. Then, it will keep looking for a second one and reaches the end. The most common scenario is also the worst-case scenario where `.Single(...)` enumerates the entire collection.

For example, on an ASP.NET application, you'd be slowing down the request for read-only pages because of a mistake on data insertion.

Unless you are testing, I don't see why you'd want to find data insertion errors when you're just reading.

I also wrote about this in the post: https://medium.com/@antao.almada/enumeration-iv-finding-an-item-ff1dc4a7467d

Thanks for the feedback! Fell free to send more.

**Comment by paulomorgado** [comment]
> The customer with id 0 is the first one and there's only one.

The customer with id 0 is the first one and **there should be only one**.

> You then use .Single(customer => customer.Id == 0) to get a customer.

You then use .Single(customer => customer.Id == 0) to get **the customer**.

> LINQ operators can only do a sequential search.

Not necessarily on all stores. Like indexed ones. Like databases.

> on an ASP.NET application, you'd be slowing down the request for read-only pages because of a mistake on data insertion.

You're favoring speed over correctness. Which one would you prefer your bank would be using? Or your country's tax services?

`First` and `Single` have semantics.

Worst than using `First` where `Single` should be used, is using `FirstOrDefault` because that one never throws.

Back to the car/parking example, (`First` vs. `Single`) there should only be 1 car with the license plate of your car because the DMV only issued 1. But you wouldn't be the first one to find out that there's at least, another car out there with the same license plate. (´FirstOrDefault´ vs. ´Single´) I don't know if you ever had your car towed or stolen, but I guarantee facing `null` is not a good felling and not an expected or acceptable result.

It is what it. You're free to use or not and in anyway you see fit. Just be sure your making an educated guess and also are not inducing others in error.

**Comment by aalmada** [comment]
@paulomorgado It's an analyzer warning giving a performance heads-up. Like any analyzer warnings, there are cases where it doesn't apply and it can be turned off (per-line, per-file, or per-project). I turn it off in my Hyperlinq project because I know I will always be testing the implementation for `Single()`.

I sure hope my bank or tax service doesn't throw exceptions. It means that they got my data wrong. What happens then? The exception is logged but what does it show to the user? Shows an error? Can I only access it after the error is fixed? Most high load sites use eventual consistency. The warning just makes you think twice about your scenario. Disable it if you're sure if that's what you want.
