### ISSUE TITLE
HLQ010 in dictionaries, is this intended?

### ISSUE THREAD

**Issue by Houtamelo** [NetFabric/NetFabric.Hyperlinq.Analyzer#74]
![image](https://github.com/NetFabric/NetFabric.Hyperlinq.Analyzer/assets/88971943/76524148-b22f-4675-82d5-b8db8316af99)

**Comment by aalmada** [comment]
Hi @Houtamelo,

When I created this rule, I believed that using the indexer would be faster than using the enumerator. However, I've since realized that this isn't always the case, especially when dealing with collections that have a value-type enumerator.

I am currently reevaluating this rule for the next version of the analyzer. For now, please consider it deprecated.
